# Generated by Django 5.0.3 on 2024-03-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='outt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('plf', models.CharField(default='', max_length=20)),
                ('date', models.DateField(default='', max_length=20)),
                ('time', models.TimeField(default='', max_length=20)),
            ],
        ),
    ]
