# Generated by Django 5.0.3 on 2024-04-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outing', '0002_remove_outt_date_remove_outt_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outt',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='outt',
            old_name='plf',
            new_name='Plf',
        ),
    ]
